host: 0.0.0.0
port: 4859
authKey: 1c04e300-1081-11eb-991
cacheSize: 4096
enableWebsocket: true
report: 
    enable: true
    groupMessage: 
        report: true
    friendMessage: 
        report: true
    tempMessage: 
        report: true
    eventMessage: 
        report: true
    destinations: []
    extraHeaders: {}

heartbeat: 
    enable: true
    delay: 1000
    period: 15000
    destinations: []
    extraBody: {}
    extraHeaders: {}

cors: ['*']